### ISSUE TITLE
Logo, icon & splashscreen preparation

### ISSUE THREAD

**Issue by danbraj** [uek-pro/bai-project#12]
Aby aplikacja pięknie wyglądała, należy przygotować przynajmniej poniższe grafiki.

- [x] logo
- [x] icon
- [x] splashscreen

Nie do końca jeszcze wiadomo jakie powinny mieć wymiary, więc byłoby cudownie gdyby były to grafiki wektorowe.

**Comment by adamusdaniel** [comment]
Chętnie odkopię Ilustratora! :)

**Comment by adamusdaniel** [comment]
Propozycje logo. Coś z tego będzie, czy myśleć dalej? (Warianty kolorystyczne do ustalenia :) )
![logo_choose](https://user-images.githubusercontent.com/23094478/38755278-6f988214-3f65-11e8-9ecb-8cc54f092d47.jpg)

**Comment by danbraj** [comment]
👍  Elegancko. W obecnej formie najbardziej imponujący jest imo nr 5. Bardzo dobrze dobrana saturacja i wykorzystanie kolorów dopełniających, super, super. Niemniej nad kolorem wiodącym trzeba się jeszcze zastanowić, gdyż będzie to też kolor akcentujący w szablonie aplikacji.

Udostępnisz plik w formacie svg?

Jeszcze tak głośno myślę, żeby można spróbować, zamiast hantla wstawić okrągłą tarczę we wbitą strzałą, podtrzymującą literkę C.

**Comment by mateBe95** [comment]
Tez mi sie wydaje ze 5 ze zmianami ktore daniel podał jest najlepsze. Zastanowilbym sie tez nad kolorami loga, bo jakie beda w nim to raczej cała aplikacja bedzie robiona pod kątem takiej kolorystyki :)

**Comment by adamusdaniel** [comment]
Kolejne propozycje :) Jak zdecydujemy się na konkretny przykład, to udostępnię plik svg :)
![logo_choose v2](https://user-images.githubusercontent.com/23094478/38772095-106efcf8-402f-11e8-9757-cac2f63de69d.jpg)

**Comment by mateBe95** [comment]
Mój faworyt numer 4 :) Ewentualnie 2 tez jest ok 👍

**Comment by danbraj** [comment]
Mi się większość podoba :D, ale powiedzmy, że podobnie jak Mati 2 i 4 ;)

**Comment by adamusdaniel** [comment]
Tutaj są przykładowe ekrany, startowy i logowania (zrobiłem w Photoshopie, jak będzie potrzeba to mogę już wybraną wersję przerzucić do Illustratora).

![index and login](https://user-images.githubusercontent.com/23094478/38775950-e3b73a80-408e-11e8-905e-d4dd4614b0dc.jpg)

Nie jestem w stanie wrzucić .sgv tutaj, więc wrzuciłem na dysk :)
https://drive.google.com/file/d/1c4F_FxXGMBT1IGe595r1jOzZRjfvIGAB/view?usp=sharing

**Comment by mateBe95** [comment]
chyba 1 motyw najbardziej, niebieski imo gryzie sie z zielonym :D

**Comment by danbraj** [comment]
Logo zatem zostało wykonane, można je wykorzystać także jako splashscreen. Pozostała jeszcze do stworzenia ikona. Trzymajmy się grafiki wektorowej, więc jedyne wymaganie to kształt kwadratu.

**Comment by adamusdaniel** [comment]
Zobaczcie moją propozycję ikony. Tarcza ze strzałą jako główny element i dodatkowo akronim nazwy apki, czyli PC. 

https://drive.google.com/open?id=167GNuTH93JIbn_R4_-ecO4KZDia7TOWO
