### ISSUE TITLE
Application name

### ISSUE THREAD

**Issue by danbraj** [uek-pro/bai-project#2]
Czołem przyjaciele,
nasza aplikacja nie ma nadanej nazwy. Trzeba coś z tym zrobić! Proszę podawać jakieś propozycje, a następnie wspólnymi siłami wybierzemy tę najlepszą.

**Comment by mateBe95** [comment]
Habit Target ?

**Comment by danbraj** [comment]
Habit Manager,
Habit Logger,
Daily Logger?

**Comment by EmSiii** [comment]
Daily logger albo habit logger jest ok

**Comment by mateBe95** [comment]
Mi sie słowo logger kojarzy z jakimś keyloggererem :D

**Comment by danbraj** [comment]
Nie zdradzaj ukrytych funkcjonalności :D

**Comment by adamusdaniel** [comment]
Mam podobne odczucia jak Mateusz :D Habit Manager dla mnie super! Ewentualnie Habit Control? Practice Control?

**Comment by danbraj** [comment]
O, Practice Control albo Habit Control mi się podoba, ale bardziej Practice Control ;D

🙋‍♂️ Practice Control po raz pierwszy..!

**Comment by EmSiii** [comment]
Po raz drugi 🙋‍♂️

**Comment by mateBe95** [comment]
3x tak
