### ISSUE TITLE
Delete btn dont work

### ISSUE THREAD

**Issue by mateBe95** [uek-pro/bai-project#23]
Przeklejam log z konsoli

![image.png](https://images.zenhubusercontent.com/5a33a9d08a75884b908b3d5c/0955b9a1-8fa7-4202-941a-f11d3903e052)

**Comment by danbraj** [comment]
Reference to 85bf0e86ec825c0b83f524117b979f983499e0d7

**Comment by danbraj** [comment]
Fix

```js
$(hHabitsList).append(
    `<li>
        <a href="#">
            <h2>${el.name}</h2>
            <p>(${el.type}) ${el.desc} - ${el.date}</p>
        </a>
        <a href="#">Delete</a>
    </li>`
);
hHabitsList.querySelectorAll('li:last-child a')[1].addEventListener('click', () => deleteHabit(keys[i]));
```

Reszta out i informacja o braku zwyczajów też out, ponieważ ona jest dodawana do elementu `hHabitsList` i przez to się sypie, gdy zostaje tylko jeden zwyczaj. Dodatkowo `$(hHabitsList).empty();` przed sprawdzeniem czy lista zwyczajów jest pusta.

**Comment by mateBe95** [comment]
Jak wyniklo z naszej rozmowy, Informacja o braku zwyczajów była powodowana przez brak  metody empty na liscie przed sprawdzeniem warunku. Problem rozwiązany z zachowaniem informacji i pustej liście. :)
