### ISSUE TITLE
Dictionary form creation

### ISSUE THREAD

**Issue by danbraj** [uek-pro/bai-project#27]
Na podstronie dodawania nowego zwyczaju, wymagane jest stworzenie formularza słownika oraz jego obsługa (zapis danych słownika do obiektu).

### Prowizoryczny wygląd formularza

![image](https://user-images.githubusercontent.com/19363013/39332435-a7a655f4-49a7-11e8-9b5e-13d4df0b724b.png)

* **X** - usuwa rekord formularza
* **+** - dodaje rekord do formularza

### Struktura obiektu z danymi formularza

```js
const dict = [
	["orginal1", "translated1"],
	["orginal2", "translated2"],
	["orginal3", "translated3"]
]
```

**Comment by mateBe95** [comment]
const dict = [
	["orginal1", "translated1"],
	["orginal2", "translated2"],
	["orginal3", "translated3"]
]
to tablica a nie obiekt? ;>

**Comment by danbraj** [comment]
Bystrzak ;D
