### ISSUE TITLE
Development of the application prototype

### ISSUE THREAD

**Issue by danbraj** [uek-pro/bai-project#3]
Cześć, ważnym elementem projektu jest opracowanie prototypu aplikacji. To jest właściwe miejsce na pokazanie swojej wizji aplikacji oraz dyskusji na jej temat.

Na dniach postaram się wrzucić moją wizję.

**Comment by adamusdaniel** [comment]
Cześć, ode mnie bardzo wczesna wersja prototypu i wizji, jak mniej więcej mogłaby wyglądać aplikacja. Nie wszystkie ekrany są tutaj zawarte, ze względu na to, że chciałbym mniej więcej pokazać, jak ja bym ją widział. Opisy poszczególnych ekranów znajdują się w środku. Powiedzcie co myślicie, co w nim zmienić i czy w ogóle taki zarys mógłby się sprawdzić.
[Prototyp v0.pdf](https://github.com/uek-pro/bai-project/files/1886480/Prototyp.v0.pdf)

**Comment by danbraj** [comment]
Generalnie jest bardzo spoko według mnie. Pozwoliłem sobie jednak przygotować moją wizję, uwzględniając przy tym Twoje pomysły. Ogólnie moim zdaniem pasowałoby raczej minimalizować ilość podstron. Patrzę pod kątem złożoności problemu do zaprogramowania, ale w gruncie rzeczy prototyp może różnić się od wersji finalnej, to też możemy postarać się stworzyć go wzorcowo xD. A zaprogramujemy i tak, tak jak będziemy umieć.

![cci09042018_1](https://user-images.githubusercontent.com/19363013/38492130-4cf7bf2e-3bee-11e8-8acc-1c9bdbe27b1e.jpg)
![cci09042018_2](https://user-images.githubusercontent.com/19363013/38492131-4d482f9a-3bee-11e8-9afb-eb0b35eb5b1b.jpg)

**Comment by adamusdaniel** [comment]
Dla mnie super :) W moim prototypie zastosowałem więcej ekranów ze względu na wygodę użytkowania (większe przyciski, pola, teksty), ale myślę, że taka wersja apki jak najbardziej jest ok :) Zresztą tak jak mówisz, wszystko wyjdzie w praniu. Mam pytanie odnośnie trybu offline. Czy będzie jakaś różnica w funkcjonowaniu aplikacji po zalogowaniu, a trybie anonimowym? Jak to będzie realizowane? 
Postaram się do końca tygodnia zrobić już jakiś klikalny prototyp tego, co na razie udało się ustalić :)  Z tego co widziałem na forum temat został zaakceptowany! :)

**Comment by danbraj** [comment]
Dążyć będziemy do tego, żeby nie było większej różnicy przy korzystaniu po zalogowaniu a offline. Wiadomo, przy działaniu offline, aplikacja nie będzie mogła zapisywać swoich danych w bazie danych na serwerze a w lokalnym magazynie. W przypadku braku połączenia z internetem, w trybie offline, niedostępna będzie tylko funkcjonalność wyświetlania sugerowanych zadań, gdyż te muszą być pobierane z serwera. Natomiast będąc zalogowanym wyświetlany zostanie komunikat o braku połączenia i powiedzmy na razie, że nie będzie można korzystać z aplikacji :p

**Comment by adamusdaniel** [comment]
www.8h4b8u.axshare.com
Pod tym linkiem znajduje się prototyp (jeszcze nie cały skończony). Chwilę trzeba poczekać, aż się załaduje :D Powiedzcie co myślicie, gdzie widać błędy. Nie mam pojęcia co dać w ustawieniach aplikacji...  Apka "uruchamia się" po kliknięciu w ekran (mogę dodać jakąś animację ładowania jeśli myślicie, że się przyda).

**Comment by danbraj** [comment]
Jest spoko ;) W ustawieniach aplikacji ustaliliśmy, że będzie przełącznik powiadomień (włączający lub wyłączający je) oraz pole z wyborem godziny powiadomienia (powiadomienie będzie globalne a nie nadawane do konkretnego zadania). Poza tym mogą się tam jeszcze pojawić dodatkowe opcje, które nie zostały jeszcze wymyślone. 

Ogólnie animacja ładowania jest potrzebna, ale jako ikona wyświetlająca się przy dłuższych operacjach aplikacji. Jeżeli jesteś w stanie stworzyć jakąś pasującą do charakteru aplikacji, byłoby przecudnie a jeśli nie, spoko znajdziemy jakąś w internecie lub stworzymy w CSS'ie sami ;)

**Comment by adamusdaniel** [comment]
Zobaczcie zmieniony prototyp:
1. Cztery loadery, dostępne na ekranie głównym. Zobaczcie proszę i wybierzcie jeden. Wg mnie 2 lub 3 :)
2. Zmodyfikowane ustawienia aplikacji.

Dzisiaj dodam też podgląd poszczególnych zadań. Pytanie jakie mi się nasuwa, czy dodajemy wykresy? Jeśli tak, to w poszczególnych zadaniach, czy jako globalny wykres osiągnięcia celu całościowego?

**Comment by danbraj** [comment]
Prototyp ok. Loader - tarcza jest bardzo spoko. A dałoby się dodać do niej efekt np. pulsowania, żeby była bardziej dynamiczna? :D

Odnośnie do podglądu zadań myślałem o tym, aby po kliknięciu na konkretne zapisane zadanie wyświetlały się szczegóły zależne od typu zadania. W niektórych znajdowałyby się właśnie kolorowe wykresy. A dokładniej:
  * Tak / Nie - 2 wykresy kołowe (ostatnie 2 tyg i od dodania zadania),
  * Z odpowiedzią - 2 wykresy kołowe (jw) + wykres liniowy a ściślej wykres warstwowy (os x - dzień, y - podana wartość)
  * Informacja - brak szczegółów
  * Mini-słownik - lista słówek

Sam wygląd wykresów wyglądałby mniej więcej tak

![g4241](https://user-images.githubusercontent.com/19363013/39095942-e80723a6-4648-11e8-99b3-4f57d5f65d85.png)

Oczywiście jest to wszystko jeszcze do uzgodnienia ;) Globalne podsumowanie będzie natomiast w formie tekstowej ew. w towarzystwie jeszcze kilku wykresów.

Btw, chodzą słuchy, że za implementację wykresów jest 0,5 stopnia więcej.

**Comment by adamusdaniel** [comment]
Zaktualizowałem trochę prototyp :)
https://8h4b8u.axshare.com/ Tutaj link dla przypomnienia :)

W statystyce zadań typu Yes/No dodałem jeszcze jeden wykres po prawej stronie, co myślicie o takim rozwiązaniu? (razem z wykresem kołowym)
Próbowałem zrobić ikonę bardziej pulsującą, jednak po tym, jak zacząłem bawić się rozmiarami ikony, .gif  mi robi białe ramki :/ Sam efekt pulsowania nie jest zbytnio widoczny, a nie chcemy chyba też robić ikony na pół ekranu :/ Dlatego myślę, że najlepiej będzie wziąć kulki :) (efekt jak poprzednio na ekranie początkowym)

I pytanie odnośnie dodawania zadania typu słownikowego. Na jakiej zasadzie to będzie realizowane? Słowniki danych języków, czy danych kategorii, czy jedno i drugie jednocześnie? Zastanawiam się jak najlepiej rozplanować ten ekran :) 

Pomijając to, wydaje mi się, że prototyp jest już w wersji dość zaawansowanej :) Jeśli któryś ekran pominąłem, proszę dajcie znać.

**Comment by danbraj** [comment]
Wykonano
