### ISSUE TITLE
Troubleshooting and last touches

### ISSUE THREAD

**Issue by danbraj** [uek-pro/bai-project#40]
Lista znanych błędów do usunięcia oraz brakujących funkcjonalności:

- [x] Przy wykresie warstwowym zamienić wartości na osi x z _relatywnych dni_ na _konkretne daty_
- [x] Typ **Mini-słownik** na podstronie z sugerowanymi zadaniami (oraz na liście zapisanych zadań?) powienien zawierać przycisk, bądź switch pokazujący/ukrywający słówka
- [x] Problem z zachowaniem się switcha o id `show-notifications` (stan nie zawsze odpowiada wartości właściwości)
- [x] Start aplikacji (nawet gdy użytkownik był zalogowany to aplikacja przechodzi przez podstronę logowania)
- [x] Podstrona globalne podsumowanie
- [x] Wykorzystać _radar chart_, gdy zapisanych jest >2 zwyczajów typu 0 lub 1 (opcjonalnie)
- [x] Zastosować licznik passy (ikonka burn? `<i class="fas fa-burn"></i>`) w szczegółach zwyczaju lub na liście zwyczajów
- [x] Dodać kilkanaście sugerowanych predefiniowanych zwyczajów różnych typów
- [ ] Edycja zapisanych zwyczajów (opcjonalnie, ale fajnie by było)
- [x] Stworzenie plików instalacyjnych aplikacji
- [x] Uzupełnienie dokumentacji

**Comment by EmSiii** [comment]
Zwyczaje gotowe, a ten licznik passy w szczegółach zwyczaju co dokładnie ma wykonywać?

**Comment by danbraj** [comment]
Zliczać serię udanej realizacji zadań. Ale spoko, już sobie poradziłem ;)

![image](https://user-images.githubusercontent.com/19363013/39876941-dce11e8e-5474-11e8-92ed-4715fe0c6f0a.png)

**Comment by EmSiii** [comment]
Ok to super :) a w podstronie globalne podsumowanie mają być ogólnie zebrane informacje o realizacji zadań?

**Comment by danbraj** [comment]
Zagadnienie to zostało rozwiązane 💪.
